export function materialUIStylings(flavor) {
  switch (flavor) {
    case "Acai":
      return "#46295a";
    case "Apple":
      return "#27ae60";
    case "Apple-cider":
      return "#e74c3c";
    case "Apricot":
      return "#f3c06e";
    case "Banana":
      return "#ffe135";
    case "Basil":
      return "#82c87e";
    case "Berry":
      return "#9b59b6";
    case "Black-tea":
      return "#e1c699";
    case "Blackberry":
      return "#37084b";
    case "Black-cherry":
      return "#52253a";
    case "Blueberry":
      return "#3498db";
    case "Cactus":
      return "#5c755e";
    case "Calamansi":
      return "#f1c40f";
    case "Cardamom":
      return "#757331";
    case "Chili":
      return "#e32227";
    case "Chai":
      return "#d1b280";
    case "Cherry":
      return "#d10202";
    case "Cinnamon":
      return "#d1b280";
    case "Citrus":
      return "greenyellow";
    case "Clementine":
      return "f39c12";
    case "Coconut":
      return "#583e00";
    case "Cola":
      return "#422801";
    case "Cranberry":
      return "#e74c3c";
    case "Cucumber":
      return "#b4f0cd";
    case "Currant":
      return "#3d3242";
    case "Dragon-fruit":
      return "#f35d8b";
    case "Elderflower":
      return "#fbf9e8";
    case "Fruit-punch":
      return "#e74c3c";
    case "Ginger":
      return "#d1b280";
    case "Grape":
      return "#8e44ad";
    case "Grapefruit":
      return "#fdb6f0";
    case "Green-tea":
      return "#2ecc71";
    case "Guava":
      return "#f17a98";
    case "Hibiscus":
      return "#e74c3c";
    case "Honey":
      return "#e79a3f";
    case "Honeysuckle":
      return "#e50068";
    case "Huckleberry":
      return "#4a4843";
    case "Key-lime":
      return "#e8f48c";
    case "Kiwi":
      return "#8ee53f";
    case "Lavender":
      return "#e6e6fa";
    case "Lemon":
      return "#fff700";
    case "Lemonade":
      return "#fff44f";
    case "Lemongrass":
      return "#9bc01c";
    case "Lemon-sorbet":
      return "#fff44f";
    case "Limoncello":
      return "#f8e71c";
    case "Lime":
      return "#bfff00";
    case "Lychee":
      return "#ffbfcd";
    case "Mandarin":
      return "#ff9f1c";
    case "Mango":
      return "#fdb462";
    case "Melon":
      return "#f69c9f";
    case "Mint":
      return "#3eb489";
    case "Mojito":
      return "#73c2fb";
    case "Mushroom":
      return "#e0c69e";
    case "Nectarine":
      return "#ff4500";
    case "Orange":
      return "#ff7f00";
    case "Orange-cream":
      return "#ffcc99";
    case "Passionfruit":
      return "#ff6f61";
    case "Peach":
      return "#ffe5b4";
    case "Pear":
      return "#d1e231";
    case "Peppermint":
      return "#3eb489";
    case "Pineapple":
      return "#ffcc00";
    case "Pink-lemonade":
      return "#ff6f52";
    case "Plain":
      return "#f8f7fc";
    case "Plum":
      return "#dda0dd";
    case "Pomelo":
      return "#fcd12a";
    case "Pomegranate":
      return "#c0392b";
    case "Raspberry":
      return "#e30b5d";
    case "Root-beer":
      return "#301934";
    case "Rose":
      return "#ff007f";
    case "Sea-berry":
      return "#ed5e93";
    case "Strawberry":
      return "#ff0066";
    case "Sweetgrass":
      return "#d4bb87";
    case "Tangerine":
      return "#f28500";
    case "Tea":
      return "#d0f0c0";
    case "Turmeric":
      return "#e1a95f";
    case "Watermelon":
      return "#fc6c85";
    case "Wildflower":
      return "#dcdcdc";
    default:
      return "";
  }
}
