export function materialUIStylings(flavor) {
  switch (flavor) {
    case "Acai":
      return "#46295a";
    case "Apple":
      return "#27ae60";
    case "Apple-cider":
      return "#e74c3c";
    case "Apricot":
      return "#f3c06e";
    case "Banana":
      return "#ffe135";
    case "Basil":
      return "#82c87e";
    case "Berry":
      return "#9b59b6";
    case "Black-tea":
      return "#e1c699";
    case "Blackberry":
      return "#37084b";
    case "Black-cherry":
      return "#52253a";
    case "Blood-orange":
      return "#e74c3c";
    case "Blueberry":
      return "#3498db";
    case "Cactus":
      return "#5c755e";
    case "Calamansi":
      return "#f1c40f";
    case "Cardamom":
      return "#757331";
    case "Chili":
      return "#e32227";
    case "Chai":
      return "#d1b280";
    case "Cherry":
      return "#d10202";
    case "Cinnamon":
      return "#d1b280";
    case "Citrus":
      return "greenyellow";
    case "Clementine":
      return "f39c12";
    case "Coconut":
      return "#583e00";
    case "Cola":
      return "#422801";
    case "Cranberry":
      return "#e74c3c";
    case "Cucumber":
      return "#b4f0cd";
    case "Currant":
      return "#3d3242";
    case "Dragon-fruit":
      return "#f35d8b";
    case "Elderflower":
      return "#fbf9e8";
    case "Fruit-punch":
      return "#e74c3c";
    case "Ginger":
      return "#d1b280";
    case "Grape":
      return "#8e44ad";
    case "Grapefruit":
      return "#fdb6f0";
    case "Green-tea":
      return "#2ecc71";
    case "Guava":
      return "#f17a98";
    case "Hibiscus":
      return "#e74c3c";
    case "Honey":
      return "#e79a3f";
    case "Honeysuckle":
      return "#e50068";
    case "Huckleberry":
      return "#353770";
    case "Key-lime":
      return "#9eeb9e";
    case "Kiwi":
      return "#a9c77e";
    case "Lavender":
      return "#e6e6fa";
    case "Lemon":
      return "#EDD012";
    case "Lemonade":
      return "#EDD012";
    case "Lemongrass":
      return "#969580";
    case "Lemon-sorbet":
      return "#EDD012";
    case "Limoncello":
      return "#EDD012";
    case "Lime":
      return "#32cd32";
    case "Lychee":
      return "#ffbfcd";
    case "Mandarin":
      return "#f39c12";
    case "Mango":
      return "#f4bb44";
    case "Melon":
      return "#fdbcb4";
    case "Mint":
      return "#2ecc71";
    case "Mojito":
      return "#7fdfa7";
    case "Mushroom":
      return "#d6ccc2";
    case "Nectarine":
      return "#eca93d";
    case "Orange":
      return "#ffa500";
    case "Orange-cream":
      return "#f39c12";
    case "Passionfruit":
      return "#81072c";
    case "Peach":
      return "#f39c12";
    case "Pear":
      return "#5af881";
    case "Peppermint":
      return "#c5eada";
    case "Pineapple":
      return "#f1c40f";
    case "Pink-lemonade":
      return "#efd3d2";
    case "Plain":
      return "#3b3b3b";
    case "Plum":
      return "#673147";
    case "Pomelo":
      return "#f39c12";
    case "Pomegranate":
      return "#c0392b";
    case "Raspberry":
      return "#e30b5c";
    case "Root-beer":
      return "#8c6a33";
    case "Rose":
      return "#ff007f";
    case "Sea-berry":
      return "#f09447";
    case "Strawberry":
      return "#e74c3c";
    case "Sweetgrass":
      return "#e7ffa4";
    case "Tangerine":
      return "#f39c12";
    case "Tea":
      return "#d0f0c0";
    case "Turmeric":
      return "#e1a95f";
    case "Vanilla":
      return "#f1c40f";

    case "Watermelon":
      return "pink";
    case "Wildflower":
      return "#dcdcdc";
    case "Yuzu":
      return "#f1c40f";

    default:
      return "";
  }
}
